### ISSUE TITLE
Tuning Results (with % m, n)

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/Smote_tune#1]
## Experiment:
- Goal - maximizing Fscore for each of 6 learners separately.
- Once the parameters are found, reporting all 5 evaluation measures.
- train, validation, and test sets.
- parameters tuned are:
    - m(20,50) and n(80,50) % of oversampling and undersampling respectively.
    - power of distance metric (r) (0.1 to 5)??
    - k=(2,20) exponential??
    - Didn't do the preprocessing part (exp = 0.3 to 3)

### Accuracy
![file](https://github.com/ai-se/Smote_tune/raw/master/Figures/Accuracy_tuned.png)

### Recall
![file](https://github.com/ai-se/Smote_tune/raw/master/Figures/Recall_tuned.png)

### Precision
![file](https://github.com/ai-se/Smote_tune/raw/master/Figures/Precision_tuned.png)

### F_score
![file](https://github.com/ai-se/Smote_tune/raw/master/Figures/F_score_tuned.png)

### False Alarm
![file](https://github.com/ai-se/Smote_tune/raw/master/Figures/False_alarm_tuned.png)

**Comment by timm** [comment]
results?
