### ISSUE TITLE
tuning per goal

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/Smote_tune#25]
- Doesn't include 3 datasets: prop, tomcat and jedit.
-  AUC(pf,pd)

## Conclusions:
- AUC the highest improvement.
- Recall good improvements
- Fscore = DT and RF most improvement
- Others either the same or worse.

### Accuracy - Maximize
![file](https://github.com/ai-se/Smote_tune/raw/master/fault_prediction/fig/Accuracy_tuned2.png)

### AUC - Maximize
![file](https://github.com/ai-se/Smote_tune/raw/master/fault_prediction/fig/AUC_tuned2.png)

### Recall - Maximize
![file](https://github.com/ai-se/Smote_tune/raw/master/fault_prediction/fig/Recall_tuned2.png)

### Precision - Maximize
![file](https://github.com/ai-se/Smote_tune/raw/master/fault_prediction/fig/Precision_tuned2.png)

### F_score - Maximize
![file](https://github.com/ai-se/Smote_tune/raw/master/fault_prediction/fig/F_score_tuned2.png)

### False Alarm - Minimise
![file](https://github.com/ai-se/Smote_tune/raw/master/fault_prediction/fig/False_alarm_tuned2.png)

**Comment by timm** [comment]
massive recall and AUC improvements at some not large false alarm increase
