### ISSUE TITLE
CK is an oo metric. what are u saying here

### ISSUE THREAD

**Issue by timm** [ai-se/Smote_tune#7]
K metrics combined with OO (object-oriented) metrics perform better than all other metrics.

**Comment by amritbhanu** [comment]
yes CK is an OO metric, and it performs better than all other OO and static attributes metric

**Comment by timm** [comment]
ck is a set  of metrics

**Comment by amritbhanu** [comment]
Ok

**Comment by amritbhanu** [comment]
But it has added advantage than other ones. I want to show why we only sticked to ck metrics
