### ISSUE TITLE
this para makes no sense

### ISSUE THREAD

**Issue by timm** [ai-se/Smote_tune#8]
Results by Tantithamthavorn et al [50] also suggested that
every  dataset  comes  with  different  attributes.  And  also  clas-
sification  techniques  often  have  configurable  parameters  that
control  characteristics  of  these  classifiers  that  they  produce.
Now time has come to even think about hyperparameter opti-
mization of these techniques and come up with an automated
process [2], [16] to tune these parameters for every dataset.

**Comment by amritbhanu** [comment]
i hope now it makes sense.

**Comment by timm** [comment]
> Results form Tantithamthavorn et al~\cite{tantithamthavorn2016automated} have suggested to configure parameters of classification learners for defect prediction since every classifiers often have configurable parameters that control characteristics of these classifiers.

???

>  According to them very dataset comes with different attributes and with different configurable learners, it is time to do hyperparameter optimization and have an automated process to tune these parameters for every dataset~\cite{agrawal2016wrong, fu2016tuning}.

???

**Comment by amritbhanu** [comment]
Wants to show why tuning is important. As there has been tuning studies done by tantithamthavorn and fu2016tuning. There is now a need to have automated techniques for tuning just like our work

**Comment by timm** [comment]
that might be the intent. but these sentences are tortured

**Comment by timm** [comment]
that might be the intent. but these sentences are tortured
